name: Changelog
on:
  push:
     branches: development
jobs:
  generatelog:
    runs-on: ubuntu-latest
    steps:
    - name: change working directory
      uses: actions/checkout@v3
    - name: Generate changelog
      run: |
          git config --global user.name 'Lagothzanta77'
          git config --global user.email 'lagothzanta77@users.noreply.github.com'
          git log -n 5 --pretty=format:"%h - %s - %ad" --date=short > changelog-hunglish.txt
          git pull
          git add changelog-hunglish.txt
          git commit --amend --no-edit
          git push origin HEAD:development
