name: HTML check
on:
  pull_request:
     branches: main
jobs:
  htmltest:
    runs-on: ubuntu-latest
    steps:
# set github directory
    - name: change working directory
      uses: actions/checkout@v2
    - name: Html check
      run: bash ./.test/test.sh
    - name: Generate changelog
    - run: git status
    - run: git log -n 5 --pretty=format:"%h - %s - %ad" --date=short > changelog-hunglish.txt 
    - run: git add changelog-hunglish.txt 
    - run: git commit --amend --no-edit 
    - run: git push --force
